services:
  postgres:
    build: ./database
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom-network

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    # volumes:
    #   - ./src:/app/src
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - custom-network

volumes:
  postgres-data:

networks:
  custom-network:
    driver: bridge
